name = "aafu"
license = "MIT"
licenselink = "https://github.com/darshanbaral/aafu/blob/master/LICENSE"
description = "Portfolio and blog theme with multiple theme colors"
homepage = "https://github.com/darshanbaral/aafu"
demosite = "https://aafu.pages.dev/"
tags = ["portfolio", "accordion", "resume", "blog", "tailwind"]
features = ["responsive", "dark", "clean"]
min_version = "0.121.1"
theme_version = "2024.01.25"

[author]
  name = "Darshan Baral"
  homepage = "https://www.darshanbaral.com/"
